[package]
name = "interview"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.29.0", features = ["socket"] }
quick-js = "0.4.1"
regex = "1.11.1"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"
